[package]
name = "imp-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
image = "0.24"
imp-backend = { path = "../backend" }
nsvg = "0.5"
plotters = "0.3"
plotters-svg = "0.3"
supports-color = "1.3"
toml = "0.5"
viuer = "0.6"
